apiVersion: apps/v1
kind: Deployment
metadata:
  name: papoder-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papoder-backend
  template:
    metadata:
      labels:
        app: papoder-backend
    spec:
      containers:
        - name: papoder-backend
          image: 183523511998.dkr.ecr.us-east-1.amazonaws.com/papoder/backend-api:latest
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: backend-srv-cluster
spec:
  type: ClusterIP
  selector:
    app: papoder-backend
  ports:
    - name: papoder-backend-cluster-ip
      protocol: TCP
      port: 4000
      targetPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: backend-lb-srv
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  selector:
    app: papoder-backend
  type: LoadBalancer
